import { useEffect, useRef, useState } from 'react';
import { speechToSign } from '../lib/api';
import type { SignPhrasePayload } from '../lib/api';
const CHUNK_MS = 4000;
const SUPPORTED_PHRASES = ['I need help', 'I need water', 'Where is the hospital', 'My name is', 'Thank you', 'I am sorry', 'Yes', 'No', 'I have pain here', 'I need medicine', 'Call my family', 'I do not understand'];
function pickMimeType(): string { for (const candidate of ['audio/webm;codecs=opus', 'audio/webm', 'audio/mp4']) if (MediaRecorder.isTypeSupported(candidate)) return candidate; return ''; }
export default function SignTranslator() {
  const [listening, setListening] = useState(false); const [transcript, setTranscript] = useState(''); const [current, setCurrent] = useState<SignPhrasePayload | null>(null); const [playing, setPlaying] = useState(false); const [missed, setMissed] = useState(''); const [error, setError] = useState('');
  const recorderRef = useRef<MediaRecorder | null>(null); const videoRef = useRef<HTMLVideoElement>(null); const loadedRef = useRef('');
  useEffect(() => () => { recorderRef.current?.stream.getTracks().forEach((t) => t.stop()); }, []);
  useEffect(() => () => { const video = videoRef.current; if (video) { video.pause(); video.removeAttribute('src'); video.load(); } loadedRef.current = ''; }, []);
  const startPlayback = (video: HTMLVideoElement) => { video.play().then(() => setPlaying(true)).catch(() => { video.muted = true; video.play().then(() => setPlaying(true)).catch(() => { setPlaying(false); setError(video.error ? 'Sign clip not found - run the clip shoot.' : 'Playback was blocked by the browser - press Play sign to start.'); }); }); };
  const stopSign = () => { const video = videoRef.current; if (!video) return; video.pause(); video.currentTime = 0; setPlaying(false); };
  const playSign = () => { const video = videoRef.current; if (!video || !current) return; video.currentTime = 0; startPlayback(video); };
  useEffect(() => { const video = videoRef.current; if (!current || !video) return; if (loadedRef.current === current.phrase_id && video.getAttribute('src')) return; loadedRef.current = current.phrase_id; video.removeAttribute('src'); video.load(); video.src = current.clip; setError(''); startPlayback(video); }, [current]);
  const sendChunk = async (blob: Blob) => { try { const result = await speechToSign(blob); if (result.transcript) { setTranscript((prev) => prev ? `${prev} ${result.transcript}` : result.transcript); setMissed(''); } if (result.phrase) setCurrent(result.phrase); else if (result.transcript) setMissed(`No sign phrase matched "${result.transcript}" (score ${result.match_score}).`); } catch { setError('Backend unreachable - is FastAPI running on port 8000?'); } };
  const start = async () => { setError(''); setTranscript(''); setMissed(''); try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const mimeType = pickMimeType(); const recorder = mimeType ? new MediaRecorder(stream, { mimeType }) : new MediaRecorder(stream); recorder.ondataavailable = (e) => { if (e.data.size > 0) void sendChunk(e.data); }; recorder.start(CHUNK_MS); recorderRef.current = recorder; setListening(true); } catch { setError('Microphone permission denied.'); } };
  const stop = () => { recorderRef.current?.stop(); recorderRef.current?.stream.getTracks().forEach((t) => t.stop()); recorderRef.current = null; setListening(false); };
  return <div className="feature-card" role="tabpanel" id="panel-sign" aria-labelledby="tab-sign"><h2>Speech to Sign Language</h2><p>Speak a supported phrase. It is transcribed live and signed in Indian Sign Language.</p><div className="chips" aria-label="Supported phrases - try saying one of these">{SUPPORTED_PHRASES.map((phrase) => <span key={phrase} className="chip chip-static">{phrase}</span>)}</div><div className="btn-row"><button className="btn" onClick={() => listening ? stop() : void start()}>{listening ? 'Stop listening' : 'Start listening'}</button></div>{error && <div className="error" role="alert">{error}</div>}<div className="result" aria-live="polite"><h3>Heard</h3><p>{transcript || '...'}</p>{missed && <p className="meta">{missed}</p>}</div><div className="sign-box"><video ref={videoRef} className="sign-video" playsInline autoPlay loop controls={false} aria-label="Sign language interpretation" />{current && <><p className="gloss" aria-live="polite">ISL gloss: {current.gloss.join(' → ')}</p><div className="btn-row">{playing ? <button className="btn btn-secondary" onClick={stopSign} aria-label="Stop sign playback">⏹ Stop</button> : <button className="btn" onClick={playSign} aria-label="Play the sign on a loop">▶ Play sign</button>}{playing && <span className="meta">↻ repeating</span>}</div></>}</div></div>;
}
